import type { GlobalThemeOverrides } from 'naive-ui'

export const naiveUiThemeOverrides: GlobalThemeOverrides = {
  // common: {
  //   baseColor: '#ffffff',
  //   bodyColor: '#ffffff',
  //   borderColor: '#e4e4e7',
  //   borderRadius: '8px',
  //   borderRadiusSmall: '6px',
  //   fontFamily: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  //   fontSize: '14px',
  //   fontSizeMedium: '14px',
  //   heightMedium: '40px',
  //   lineHeight: '1.5',
  //   placeholderColor: '#a1a1a1',
  //   primaryColor: '#18181b',
  //   primaryColorHover: '#27272a',
  //   primaryColorPressed: '#09090b',
  //   primaryColorSuppl: '#3f3f46',
  //   textColorBase: '#18181b',
  //   textColor1: '#18181b',
  //   textColor2: '#3f3f46',
  //   textColor3: '#71717a',
  // },
  // Button: {
  //   border: '1px solid #e4e4e7',
  //   borderHover: '1px solid #d4d4d8',
  //   borderPressed: '1px solid #a1a1a1',
  //   borderPrimary: '1px solid #18181b',
  //   borderRadiusMedium: '8px',
  //   boxShadow: 'none',
  //   boxShadowFocus: '0 0 0 2px rgba(24, 24, 27, 0.12)',
  //   fontWeight: '500',
  //   heightMedium: '40px',
  //   paddingMedium: '0 16px',
  //   textColor: '#18181b',
  //   textColorHover: '#18181b',
  //   textColorHoverPrimary: '#ffffff',
  //   textColorPressed: '#18181b',
  //   textColorPressedPrimary: '#ffffff',
  //   textColorPrimary: '#ffffff',
  // },
  // Checkbox: {
  //   border: '1px solid #d4d4d8',
  //   borderChecked: '1px solid #18181b',
  //   borderFocus: '1px solid #18181b',
  //   borderRadius: '4px',
  //   boxShadowFocus: '0 0 0 2px rgba(24, 24, 27, 0.12)',
  //   colorChecked: '#18181b',
  //   colorTableHeaderModal: '#ffffff',
  //   colorTableHeaderPopover: '#ffffff',
  //   textColor: '#18181b',
  // },
  // DatePicker: {
  //   itemColorDisabled: '#f4f4f5',
  //   itemColorHover: '#f4f4f5',
  //   itemTextColorActive: '#ffffff',
  //   itemTextColorCurrent: '#18181b',
  //   panelBorderRadius: '8px',
  //   peers: {
  //     Input: {
  //       border: '1px solid #e4e4e7',
  //       borderFocus: '1px solid #a1a1a1',
  //       borderHover: '1px solid #a1a1a1',
  //       borderRadius: '8px',
  //       boxShadowFocus: '0 0 0 2px rgba(24, 24, 27, 0.12)',
  //       heightMedium: '40px',
  //     },
  //   },
  // },
  // Form: {
  //   labelFontSizeLeftMedium: '14px',
  //   labelTextColor: '#3f3f46',
  // },
  // Input: {
  //   border: '1px solid #e4e4e7',
  //   borderFocus: '1px solid #a1a1a1',
  //   borderHover: '1px solid #a1a1a1',
  //   borderRadius: '8px',
  //   boxShadowFocus: '0 0 0 2px rgba(24, 24, 27, 0.12)',
  //   heightMedium: '40px',
  //   paddingMedium: '0 12px',
  //   textColor: '#18181b',
  // },
  // Select: {
  //   peers: {
  //     InternalSelectMenu: {
  //       borderRadius: '8px',
  //       optionColorActive: '#f4f4f5',
  //       optionColorPending: '#f4f4f5',
  //       optionTextColorActive: '#18181b',
  //     },
  //     InternalSelection: {
  //       border: '1px solid #e4e4e7',
  //       borderActive: '1px solid #a1a1a1',
  //       borderHover: '1px solid #a1a1a1',
  //       borderRadius: '8px',
  //       boxShadowActive: '0 0 0 2px rgba(24, 24, 27, 0.12)',
  //       heightMedium: '40px',
  //     },
  //   },
  // },
  // Switch: {
  //   boxShadowFocus: '0 0 0 2px rgba(24, 24, 27, 0.12)',
  //   railColor: '#e4e4e7',
  //   railColorActive: '#18181b',
  // },
}
